name: Rotate & Submit URLs to Google Indexing API

# --- WHEN IT RUNS ----------------------------------------------------
# ➊ Every weekday at 13:00 UTC (≈ 8 AM EST)
# ➋ And anytime you click “Run workflow” manually
on:
  schedule:
    - cron: '0 13 * * 1-5'
  workflow_dispatch:

# --- WHAT IT DOES ----------------------------------------------------
jobs:
  rotate-and-submit:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: '3.11'
      URLS_CSV_PATH: indexing/urls_rotating.csv

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        pip install pandas google-api-python-client google-auth-httplib2 google-auth-oauthlib

    - name: Write GCP credentials file
      run: |
        echo "${{ secrets.GCP_INDEXING_KEY }}" > gcp_key.json

    - name: Generate urls_rotating.csv
      run: python indexing/generate_rotating_urls.py

    - name: Submit URLs (max 200) to Indexing API
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS=gcp_key.json
        python indexing/daily_submit.py

    - name: Upload log.csv as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: indexing-log-${{ github.run_id }}
        path: indexing/log.csv

