name: Rotate & Submit URLs to Google Indexing API

# --- WHEN IT RUNS ----------------------------------------------------
# ➊ Every weekday at 13:00 UTC  (≈ 08:00 EST)
# ➋ Any time you click “Run workflow” manually
on:
  schedule:
    - cron: '0 13 * * 1-5'
  workflow_dispatch:

# --- WHAT IT DOES ----------------------------------------------------
jobs:
  rotate-and-submit:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: '3.11'
      URLS_CSV_PATH: indexing/urls_rotating.csv   # read by daily_submit.py

    steps:
    # 1️⃣ Check out repo
    - name: Check out repo
      uses: actions/checkout@v4

    # 2️⃣ Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    # 3️⃣ Install Python deps (jq no longer needed)
    - name: Install dependencies
      run: |
        pip install pandas \
                    google-api-python-client \
                    google-auth-httplib2 \
                    google-auth-oauthlib

    # 4️⃣ Expose the service-account JSON to Python **via env var**
    #    • GCP_KEY_JSON is the one-line, minified JSON you saved as a secret.
    - name: Export GCP_KEY_JSON for Python
      env:
        GCP_KEY_JSON: ${{ secrets.GCP_KEY_JSON }}
      run: echo "GCP key env var set"

    # 5️⃣ Generate today’s urls_rotating.csv
    - name: Generate urls_rotating.csv
      run: python indexing/generate_rotating_urls.py

    # 6️⃣ Submit URLs (max 200) to the Indexing API
    - name: Submit URLs (max 200) to Indexing API
      run: python indexing/daily_submit.py

    # 7️⃣ Upload log as an artifact
    - name: Upload log.csv as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: indexing-log-${{ github.run_id }}
        path: indexing/log.csv


